@extends('home.dashboard.layout.master')
@section($content)
    @switch($content)
        @case('general')
            @include('home.dashboard.layout.general')
            @break
        @case('appearance')
            @include('home.dashboard.layout.appearance')
            @break
        @case('navbar')
            @include('home.dashboard.layout.navbar-setting')
            @break
        @case('article')
            @include('home.dashboard.layout.article')
            @break
        @case('series')
            @include('home.dashboard.series.index')
            @break
        @case('create-series')
            @include('home.dashboard.series.create')
            @break
        @case('pages')
            @include('home.dashboard.pages.index')
            @break
        @case('create-pages')
            @include('home.dashboard.pages.create')
            @break
        @case('tag-multi-link')
            @include('home.dashboard.tag-multi-link.index')
            @break
        @case('create-tag')
            @include('home.dashboard.tag-multi-link.create')
            @break
        @default
            @include('home.dashboard.layout.general')
            @break
    @endswitch
@endsection
